apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2026-03-17T10:06:15Z'
  generation: 1
  labels:
    run: edit-demo
  name: edit-demo
  namespace: default
  resourceVersion: '494407'
  uid: da3f736f-cf00-4212-afc9-09035b9a3c1d
spec:
  containers:
    - env:
        - name: LOG_LEVEL
          value: info
      image: nginx:1.28
      imagePullPolicy: IfNotPresent
      name: edit-demo
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-pjwdv
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: conformance-worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-pjwdv
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2026-03-17T10:06:17Z'
      observedGeneration: 1
      status: 'True'
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: '2026-03-17T10:06:15Z'
      observedGeneration: 1
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2026-03-17T10:06:17Z'
      observedGeneration: 1
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2026-03-17T10:06:17Z'
      observedGeneration: 1
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2026-03-17T10:06:15Z'
      observedGeneration: 1
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://7c482d7bf2402543c4c36ea8868a907713dc25d45b8c84282d49d5f34e415f76
      image: docker.io/library/nginx:1.28
      imageID: docker.io/library/nginx@sha256:810ad1346ec7fd3d0a246c178f2b82e73a43640c691774405adfd38a751ecce8
      lastState: {}
      name: edit-demo
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: '2026-03-17T10:06:16Z'
      user:
        linux:
          gid: 0
          supplementalGroups:
            - 0
          uid: 0
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-pjwdv
          readOnly: true
          recursiveReadOnly: Disabled
  hostIP: 172.18.0.4
  hostIPs:
    - ip: 172.18.0.4
  observedGeneration: 1
  phase: Running
  podIP: 10.244.2.2
  podIPs:
    - ip: 10.244.2.2
  qosClass: BestEffort
  startTime: '2026-03-17T10:06:15Z'
