apiVersion: v1
kind: Pod
metadata:
  name: api-prod
  namespace: production
  labels:
    app: api
    env: production
spec:
  containers:
    - name: api
      image: nginx:latest
      ports:
        - containerPort: 8080
