apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
  namespace: default
  labels:
    app: broken
spec:
  containers:
    - name: broken-container
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - exit 1
