apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
  namespace: default
  labels:
    app: pending
spec:
  containers:
    - name: pending-container
      image: nginx:latest
      resources:
        requests:
          cpu: 999999
          memory: 999999Gi
