apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
    role: master
spec:
  nodeName: default-worker-1
  containers:
    - name: redis
      image: redis:7.0-alpine
      ports:
        - containerPort: 6379
