apiVersion: v1
kind: Pod
metadata:
  name: web-staging
  namespace: staging
  labels:
    app: nginx
    env: staging
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
