apiVersion: v1
kind: Pod
metadata:
  name: web-prod
  namespace: production
  labels:
    app: nginx
    env: production
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
