// Code generated by bin/generate-cluster-resources.ts. DO NOT EDIT.

import type { ResourceKind } from '../../cluster/generated/clusterResourceTypes.generated'

// Kubectl resources: canonical name -> list of aliases
export const KUBECTL_RESOURCES = {
  all: ["all"],
  pods: ["pods","pod","po"],
  configmaps: ["configmaps","configmap","cm"],
  controllerrevisions: ["controllerrevisions","controllerrevision","rev"],
  secrets: ["secrets","secret"],
  nodes: ["nodes","node","no"],
  replicasets: ["replicasets","replicaset","rs"],
  deployments: ["deployments","deployment","deploy"],
  daemonsets: ["daemonsets","daemonset","ds"],
  statefulsets: ["statefulsets","statefulset","sts"],
  services: ["services","service","svc"],
  endpointslices: ["endpointslices","endpointslice"],
  endpoints: ["endpoints","endpoint","ep"],
  events: ["events","event","ev"],
  ingresses: ["ingresses","ingress","ing"],
  ingressclasses: ["ingressclasses","ingressclass"],
  networkpolicies: ["networkpolicies","networkpolicy","netpol"],
  gatewayclasses: ["gatewayclasses","gatewayclass","gc"],
  gateways: ["gateways","gateway","gw"],
  httproutes: ["httproutes","httproute","hr"],
  persistentvolumes: ["persistentvolumes","persistentvolume","pv"],
  persistentvolumeclaims: ["persistentvolumeclaims","persistentvolumeclaim","pvc"],
  namespaces: ["namespaces","namespace","ns"],
  leases: ["leases","lease"],
  storageclasses: ["storageclasses","storageclass","sc"],
} as const

export type KubectlResource = keyof typeof KUBECTL_RESOURCES

export const SUPPORTED_RESOURCE_KINDS: ResourceKind[] = [
  "Pod",
  "ConfigMap",
  "ControllerRevision",
  "Secret",
  "Node",
  "ReplicaSet",
  "Deployment",
  "DaemonSet",
  "StatefulSet",
  "Service",
  "EndpointSlice",
  "Endpoints",
  "Event",
  "Ingress",
  "IngressClass",
  "NetworkPolicy",
  "GatewayClass",
  "Gateway",
  "HTTPRoute",
  "PersistentVolume",
  "PersistentVolumeClaim",
  "Namespace",
  "Lease",
  "StorageClass"
]

export const NAMESPACED_RESOURCE_KINDS: ResourceKind[] = [
  "Pod",
  "ConfigMap",
  "ControllerRevision",
  "Secret",
  "ReplicaSet",
  "Deployment",
  "DaemonSet",
  "StatefulSet",
  "Service",
  "EndpointSlice",
  "Endpoints",
  "Event",
  "Ingress",
  "NetworkPolicy",
  "Gateway",
  "HTTPRoute",
  "PersistentVolumeClaim",
  "Lease"
]

export const RESOURCE_KIND_BY_RESOURCE: Record<
  KubectlResource,
  ResourceKind | undefined
> = {
  all: undefined,
  pods: "Pod",
  configmaps: "ConfigMap",
  controllerrevisions: "ControllerRevision",
  secrets: "Secret",
  nodes: "Node",
  replicasets: "ReplicaSet",
  deployments: "Deployment",
  daemonsets: "DaemonSet",
  statefulsets: "StatefulSet",
  services: "Service",
  endpointslices: "EndpointSlice",
  endpoints: "Endpoints",
  events: "Event",
  ingresses: "Ingress",
  ingressclasses: "IngressClass",
  networkpolicies: "NetworkPolicy",
  gatewayclasses: "GatewayClass",
  gateways: "Gateway",
  httproutes: "HTTPRoute",
  persistentvolumes: "PersistentVolume",
  persistentvolumeclaims: "PersistentVolumeClaim",
  namespaces: "Namespace",
  leases: "Lease",
  storageclasses: "StorageClass",
}

export const KIND_REFERENCE_BY_KIND: Record<ResourceKind, string> = {
  Pod: "pod",
  ConfigMap: "configmap",
  ControllerRevision: "controllerrevision.apps",
  Secret: "secret",
  Node: "node",
  ReplicaSet: "replicaset.apps",
  Deployment: "deployment.apps",
  DaemonSet: "daemonset.apps",
  StatefulSet: "statefulset.apps",
  Service: "service",
  EndpointSlice: "endpointslice.discovery.k8s.io",
  Endpoints: "endpoints",
  Event: "event",
  Ingress: "ingress.networking.k8s.io",
  IngressClass: "ingressclass.networking.k8s.io",
  NetworkPolicy: "networkpolicy.networking.k8s.io",
  GatewayClass: "gatewayclass.gateway.networking.k8s.io",
  Gateway: "gateway.gateway.networking.k8s.io",
  HTTPRoute: "httproute.gateway.networking.k8s.io",
  PersistentVolume: "persistentvolume",
  PersistentVolumeClaim: "persistentvolumeclaim",
  Namespace: "namespace",
  Lease: "lease",
  StorageClass: "storageclass.storage.k8s.io"
}

export const PLURAL_KIND_REFERENCE_BY_KIND: Record<ResourceKind, string> = {
  Pod: "pods",
  ConfigMap: "configmaps",
  ControllerRevision: "controllerrevisions.apps",
  Secret: "secrets",
  Node: "nodes",
  ReplicaSet: "replicasets.apps",
  Deployment: "deployments.apps",
  DaemonSet: "daemonsets.apps",
  StatefulSet: "statefulsets.apps",
  Service: "services",
  EndpointSlice: "endpointslices.discovery.k8s.io",
  Endpoints: "endpoints",
  Event: "events",
  Ingress: "ingresses.networking.k8s.io",
  IngressClass: "ingressclasses.networking.k8s.io",
  NetworkPolicy: "networkpolicies.networking.k8s.io",
  GatewayClass: "gatewayclasses.gateway.networking.k8s.io",
  Gateway: "gateways.gateway.networking.k8s.io",
  HTTPRoute: "httproutes.gateway.networking.k8s.io",
  PersistentVolume: "persistentvolumes",
  PersistentVolumeClaim: "persistentvolumeclaims",
  Namespace: "namespaces",
  Lease: "leases",
  StorageClass: "storageclasses.storage.k8s.io"
}

export const RESOURCE_OUTPUT_METADATA_BY_RESOURCE: Record<
  Exclude<KubectlResource, 'all'>,
  { apiVersion: string; kind: string }
> = {
  pods: { apiVersion: "v1", kind: "Pod" },
  configmaps: { apiVersion: "v1", kind: "ConfigMap" },
  controllerrevisions: { apiVersion: "apps/v1", kind: "ControllerRevision" },
  secrets: { apiVersion: "v1", kind: "Secret" },
  nodes: { apiVersion: "v1", kind: "Node" },
  replicasets: { apiVersion: "apps/v1", kind: "ReplicaSet" },
  deployments: { apiVersion: "apps/v1", kind: "Deployment" },
  daemonsets: { apiVersion: "apps/v1", kind: "DaemonSet" },
  statefulsets: { apiVersion: "apps/v1", kind: "StatefulSet" },
  services: { apiVersion: "v1", kind: "Service" },
  endpointslices: { apiVersion: "discovery.k8s.io/v1", kind: "EndpointSlice" },
  endpoints: { apiVersion: "v1", kind: "Endpoints" },
  events: { apiVersion: "v1", kind: "Event" },
  ingresses: { apiVersion: "networking.k8s.io/v1", kind: "Ingress" },
  ingressclasses: { apiVersion: "networking.k8s.io/v1", kind: "IngressClass" },
  networkpolicies: { apiVersion: "networking.k8s.io/v1", kind: "NetworkPolicy" },
  gatewayclasses: { apiVersion: "gateway.networking.k8s.io/v1", kind: "GatewayClass" },
  gateways: { apiVersion: "gateway.networking.k8s.io/v1", kind: "Gateway" },
  httproutes: { apiVersion: "gateway.networking.k8s.io/v1", kind: "HTTPRoute" },
  persistentvolumes: { apiVersion: "v1", kind: "PersistentVolume" },
  persistentvolumeclaims: { apiVersion: "v1", kind: "PersistentVolumeClaim" },
  namespaces: { apiVersion: "v1", kind: "Namespace" },
  leases: { apiVersion: "coordination.k8s.io/v1", kind: "Lease" },
  storageclasses: { apiVersion: "storage.k8s.io/v1", kind: "StorageClass" },
}

export const RESOURCE_DISCOVERY_REF_BY_RESOURCE: Partial<
  Record<KubectlResource, { singular: string; plural: string }>
> = {

}

export const DELETABLE_KUBECTL_RESOURCES = [
  "pods",
  "configmaps",
  "secrets",
  "nodes",
  "replicasets",
  "deployments",
  "daemonsets",
  "statefulsets",
  "services",
  "ingresses",
  "ingressclasses",
  "networkpolicies",
  "gatewayclasses",
  "gateways",
  "httproutes",
  "persistentvolumes",
  "persistentvolumeclaims",
  "namespaces",
  "leases"
] as const
