// Code generated by bin/generate-cluster-resources.ts. DO NOT EDIT.

import type { ClusterEvent } from '../../../cluster/events/types'
import type { Resource } from '../../../kubectl/commands/types'

export const extractMetaFromGeneratedClusterEvent = (
  event: ClusterEvent,
  parsedResource: Resource
): { name: string; namespace: string; labels?: Record<string, string> } | undefined => {
  if (parsedResource === 'pods') {
    if (event.type === 'PodDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedPod.metadata.labels
      }
    }
    if (event.type === 'PodCreated') {
      return {
        name: event.payload.pod.metadata.name,
        namespace: event.payload.pod.metadata.namespace,
        labels: event.payload.pod.metadata.labels
      }
    }
    if (event.type === 'PodUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.pod.metadata.labels
      }
    }
  }
  if (parsedResource === 'configmaps') {
    if (event.type === 'ConfigMapDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedConfigMap.metadata.labels
      }
    }
    if (event.type === 'ConfigMapCreated') {
      return {
        name: event.payload.configMap.metadata.name,
        namespace: event.payload.configMap.metadata.namespace,
        labels: event.payload.configMap.metadata.labels
      }
    }
    if (event.type === 'ConfigMapUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.configMap.metadata.labels
      }
    }
  }
  if (parsedResource === 'controllerrevisions') {
    if (event.type === 'ControllerRevisionDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedControllerRevision.metadata.labels
      }
    }
    if (event.type === 'ControllerRevisionCreated') {
      return {
        name: event.payload.controllerRevision.metadata.name,
        namespace: event.payload.controllerRevision.metadata.namespace,
        labels: event.payload.controllerRevision.metadata.labels
      }
    }
    if (event.type === 'ControllerRevisionUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.controllerRevision.metadata.labels
      }
    }
  }
  if (parsedResource === 'secrets') {
    if (event.type === 'SecretDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedSecret.metadata.labels
      }
    }
    if (event.type === 'SecretCreated') {
      return {
        name: event.payload.secret.metadata.name,
        namespace: event.payload.secret.metadata.namespace,
        labels: event.payload.secret.metadata.labels
      }
    }
    if (event.type === 'SecretUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.secret.metadata.labels
      }
    }
  }
  if (parsedResource === 'nodes') {
    if (event.type === 'NodeDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedNode.metadata.labels
      }
    }
    if (event.type === 'NodeCreated') {
      return {
        name: event.payload.node.metadata.name,
        namespace: '',
        labels: event.payload.node.metadata.labels
      }
    }
    if (event.type === 'NodeUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.node.metadata.labels
      }
    }
  }
  if (parsedResource === 'replicasets') {
    if (event.type === 'ReplicaSetDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedReplicaSet.metadata.labels
      }
    }
    if (event.type === 'ReplicaSetCreated') {
      return {
        name: event.payload.replicaSet.metadata.name,
        namespace: event.payload.replicaSet.metadata.namespace,
        labels: event.payload.replicaSet.metadata.labels
      }
    }
    if (event.type === 'ReplicaSetUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.replicaSet.metadata.labels
      }
    }
  }
  if (parsedResource === 'deployments') {
    if (event.type === 'DeploymentDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedDeployment.metadata.labels
      }
    }
    if (event.type === 'DeploymentCreated') {
      return {
        name: event.payload.deployment.metadata.name,
        namespace: event.payload.deployment.metadata.namespace,
        labels: event.payload.deployment.metadata.labels
      }
    }
    if (event.type === 'DeploymentUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deployment.metadata.labels
      }
    }
  }
  if (parsedResource === 'daemonsets') {
    if (event.type === 'DaemonSetDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedDaemonSet.metadata.labels
      }
    }
    if (event.type === 'DaemonSetCreated') {
      return {
        name: event.payload.daemonSet.metadata.name,
        namespace: event.payload.daemonSet.metadata.namespace,
        labels: event.payload.daemonSet.metadata.labels
      }
    }
    if (event.type === 'DaemonSetUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.daemonSet.metadata.labels
      }
    }
  }
  if (parsedResource === 'statefulsets') {
    if (event.type === 'StatefulSetDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedStatefulSet.metadata.labels
      }
    }
    if (event.type === 'StatefulSetCreated') {
      return {
        name: event.payload.statefulSet.metadata.name,
        namespace: event.payload.statefulSet.metadata.namespace,
        labels: event.payload.statefulSet.metadata.labels
      }
    }
    if (event.type === 'StatefulSetUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.statefulSet.metadata.labels
      }
    }
  }
  if (parsedResource === 'services') {
    if (event.type === 'ServiceDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedService.metadata.labels
      }
    }
    if (event.type === 'ServiceCreated') {
      return {
        name: event.payload.service.metadata.name,
        namespace: event.payload.service.metadata.namespace,
        labels: event.payload.service.metadata.labels
      }
    }
    if (event.type === 'ServiceUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.service.metadata.labels
      }
    }
  }
  if (parsedResource === 'endpointslices') {
    if (event.type === 'EndpointSliceDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedEndpointSlice.metadata.labels
      }
    }
    if (event.type === 'EndpointSliceCreated') {
      return {
        name: event.payload.endpointSlice.metadata.name,
        namespace: event.payload.endpointSlice.metadata.namespace,
        labels: event.payload.endpointSlice.metadata.labels
      }
    }
    if (event.type === 'EndpointSliceUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.endpointSlice.metadata.labels
      }
    }
  }
  if (parsedResource === 'endpoints') {
    if (event.type === 'EndpointsDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedEndpoints.metadata.labels
      }
    }
    if (event.type === 'EndpointsCreated') {
      return {
        name: event.payload.endpoints.metadata.name,
        namespace: event.payload.endpoints.metadata.namespace,
        labels: event.payload.endpoints.metadata.labels
      }
    }
    if (event.type === 'EndpointsUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.endpoints.metadata.labels
      }
    }
  }
  if (parsedResource === 'events') {
    if (event.type === 'EventDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: undefined
      }
    }
    if (event.type === 'EventCreated') {
      return {
        name: event.payload.event.metadata.name,
        namespace: event.payload.event.metadata.namespace,
        labels: undefined
      }
    }
    if (event.type === 'EventUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: undefined
      }
    }
  }
  if (parsedResource === 'ingresses') {
    if (event.type === 'IngressDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedIngress.metadata.labels
      }
    }
    if (event.type === 'IngressCreated') {
      return {
        name: event.payload.ingress.metadata.name,
        namespace: event.payload.ingress.metadata.namespace,
        labels: event.payload.ingress.metadata.labels
      }
    }
    if (event.type === 'IngressUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.ingress.metadata.labels
      }
    }
  }
  if (parsedResource === 'ingressclasses') {
    if (event.type === 'IngressClassDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedIngressClass.metadata.labels
      }
    }
    if (event.type === 'IngressClassCreated') {
      return {
        name: event.payload.ingressClass.metadata.name,
        namespace: '',
        labels: event.payload.ingressClass.metadata.labels
      }
    }
    if (event.type === 'IngressClassUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.ingressClass.metadata.labels
      }
    }
  }
  if (parsedResource === 'networkpolicies') {
    if (event.type === 'NetworkPolicyDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedNetworkPolicy.metadata.labels
      }
    }
    if (event.type === 'NetworkPolicyCreated') {
      return {
        name: event.payload.networkPolicy.metadata.name,
        namespace: event.payload.networkPolicy.metadata.namespace,
        labels: event.payload.networkPolicy.metadata.labels
      }
    }
    if (event.type === 'NetworkPolicyUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.networkPolicy.metadata.labels
      }
    }
  }
  if (parsedResource === 'gatewayclasses') {
    if (event.type === 'GatewayClassDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedGatewayClass.metadata.labels
      }
    }
    if (event.type === 'GatewayClassCreated') {
      return {
        name: event.payload.gatewayClass.metadata.name,
        namespace: '',
        labels: event.payload.gatewayClass.metadata.labels
      }
    }
    if (event.type === 'GatewayClassUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.gatewayClass.metadata.labels
      }
    }
  }
  if (parsedResource === 'gateways') {
    if (event.type === 'GatewayDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedGateway.metadata.labels
      }
    }
    if (event.type === 'GatewayCreated') {
      return {
        name: event.payload.gateway.metadata.name,
        namespace: event.payload.gateway.metadata.namespace,
        labels: event.payload.gateway.metadata.labels
      }
    }
    if (event.type === 'GatewayUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.gateway.metadata.labels
      }
    }
  }
  if (parsedResource === 'httproutes') {
    if (event.type === 'HTTPRouteDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedHTTPRoute.metadata.labels
      }
    }
    if (event.type === 'HTTPRouteCreated') {
      return {
        name: event.payload.httpRoute.metadata.name,
        namespace: event.payload.httpRoute.metadata.namespace,
        labels: event.payload.httpRoute.metadata.labels
      }
    }
    if (event.type === 'HTTPRouteUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.httpRoute.metadata.labels
      }
    }
  }
  if (parsedResource === 'persistentvolumes') {
    if (event.type === 'PersistentVolumeDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedPersistentVolume.metadata.labels
      }
    }
    if (event.type === 'PersistentVolumeCreated') {
      return {
        name: event.payload.persistentVolume.metadata.name,
        namespace: '',
        labels: event.payload.persistentVolume.metadata.labels
      }
    }
    if (event.type === 'PersistentVolumeUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.persistentVolume.metadata.labels
      }
    }
  }
  if (parsedResource === 'persistentvolumeclaims') {
    if (event.type === 'PersistentVolumeClaimDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedPersistentVolumeClaim.metadata.labels
      }
    }
    if (event.type === 'PersistentVolumeClaimCreated') {
      return {
        name: event.payload.persistentVolumeClaim.metadata.name,
        namespace: event.payload.persistentVolumeClaim.metadata.namespace,
        labels: event.payload.persistentVolumeClaim.metadata.labels
      }
    }
    if (event.type === 'PersistentVolumeClaimUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.persistentVolumeClaim.metadata.labels
      }
    }
  }
  if (parsedResource === 'namespaces') {
    if (event.type === 'NamespaceDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedNamespace.metadata.labels
      }
    }
    if (event.type === 'NamespaceCreated') {
      return {
        name: event.payload.namespace.metadata.name,
        namespace: '',
        labels: event.payload.namespace.metadata.labels
      }
    }
    if (event.type === 'NamespaceUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.namespace.metadata.labels
      }
    }
  }
  if (parsedResource === 'leases') {
    if (event.type === 'LeaseDeleted') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.deletedLease.metadata.labels
      }
    }
    if (event.type === 'LeaseCreated') {
      return {
        name: event.payload.lease.metadata.name,
        namespace: event.payload.lease.metadata.namespace,
        labels: event.payload.lease.metadata.labels
      }
    }
    if (event.type === 'LeaseUpdated') {
      return {
        name: event.payload.name,
        namespace: event.payload.namespace,
        labels: event.payload.lease.metadata.labels
      }
    }
  }
  if (parsedResource === 'storageclasses') {
    if (event.type === 'StorageClassDeleted') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.deletedStorageClass.metadata.labels
      }
    }
    if (event.type === 'StorageClassCreated') {
      return {
        name: event.payload.storageClass.metadata.name,
        namespace: '',
        labels: event.payload.storageClass.metadata.labels
      }
    }
    if (event.type === 'StorageClassUpdated') {
      return {
        name: event.payload.name,
        namespace: '',
        labels: event.payload.storageClass.metadata.labels
      }
    }
  }
  return undefined
}
