apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
  labels:
    app: api
    env: production
spec:
  type: ClusterIP
  selector:
    app: api
    env: production
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
