// Code generated by bin/generate-cluster-resources.ts. DO NOT EDIT.

import type { BaseEvent } from '../../events/types'
import type { ClusterResourceTypeByKind } from '../generated/clusterResourceModels.generated'

export interface PodCreatedEvent extends BaseEvent {
  type: 'PodCreated'
  payload: {
    pod: ClusterResourceTypeByKind['Pod']
  }
}

export interface PodDeletedEvent extends BaseEvent {
  type: 'PodDeleted'
  payload: {
    name: string
    namespace: string
    deletedPod: ClusterResourceTypeByKind['Pod']
  }
}

export interface PodUpdatedEvent extends BaseEvent {
  type: 'PodUpdated'
  payload: {
    name: string
    namespace: string
    pod: ClusterResourceTypeByKind['Pod']
    previousPod: ClusterResourceTypeByKind['Pod']
  }
}

export interface ConfigMapCreatedEvent extends BaseEvent {
  type: 'ConfigMapCreated'
  payload: {
    configMap: ClusterResourceTypeByKind['ConfigMap']
  }
}

export interface ConfigMapDeletedEvent extends BaseEvent {
  type: 'ConfigMapDeleted'
  payload: {
    name: string
    namespace: string
    deletedConfigMap: ClusterResourceTypeByKind['ConfigMap']
  }
}

export interface ConfigMapUpdatedEvent extends BaseEvent {
  type: 'ConfigMapUpdated'
  payload: {
    name: string
    namespace: string
    configMap: ClusterResourceTypeByKind['ConfigMap']
    previousConfigMap: ClusterResourceTypeByKind['ConfigMap']
  }
}

export interface ControllerRevisionCreatedEvent extends BaseEvent {
  type: 'ControllerRevisionCreated'
  payload: {
    controllerRevision: ClusterResourceTypeByKind['ControllerRevision']
  }
}

export interface ControllerRevisionDeletedEvent extends BaseEvent {
  type: 'ControllerRevisionDeleted'
  payload: {
    name: string
    namespace: string
    deletedControllerRevision: ClusterResourceTypeByKind['ControllerRevision']
  }
}

export interface ControllerRevisionUpdatedEvent extends BaseEvent {
  type: 'ControllerRevisionUpdated'
  payload: {
    name: string
    namespace: string
    controllerRevision: ClusterResourceTypeByKind['ControllerRevision']
    previousControllerRevision: ClusterResourceTypeByKind['ControllerRevision']
  }
}

export interface SecretCreatedEvent extends BaseEvent {
  type: 'SecretCreated'
  payload: {
    secret: ClusterResourceTypeByKind['Secret']
  }
}

export interface SecretDeletedEvent extends BaseEvent {
  type: 'SecretDeleted'
  payload: {
    name: string
    namespace: string
    deletedSecret: ClusterResourceTypeByKind['Secret']
  }
}

export interface SecretUpdatedEvent extends BaseEvent {
  type: 'SecretUpdated'
  payload: {
    name: string
    namespace: string
    secret: ClusterResourceTypeByKind['Secret']
    previousSecret: ClusterResourceTypeByKind['Secret']
  }
}

export interface NodeCreatedEvent extends BaseEvent {
  type: 'NodeCreated'
  payload: {
    node: ClusterResourceTypeByKind['Node']
  }
}

export interface NodeDeletedEvent extends BaseEvent {
  type: 'NodeDeleted'
  payload: {
    name: string
    deletedNode: ClusterResourceTypeByKind['Node']
  }
}

export interface NodeUpdatedEvent extends BaseEvent {
  type: 'NodeUpdated'
  payload: {
    name: string
    node: ClusterResourceTypeByKind['Node']
    previousNode: ClusterResourceTypeByKind['Node']
  }
}

export interface ReplicaSetCreatedEvent extends BaseEvent {
  type: 'ReplicaSetCreated'
  payload: {
    replicaSet: ClusterResourceTypeByKind['ReplicaSet']
  }
}

export interface ReplicaSetDeletedEvent extends BaseEvent {
  type: 'ReplicaSetDeleted'
  payload: {
    name: string
    namespace: string
    deletedReplicaSet: ClusterResourceTypeByKind['ReplicaSet']
  }
}

export interface ReplicaSetUpdatedEvent extends BaseEvent {
  type: 'ReplicaSetUpdated'
  payload: {
    name: string
    namespace: string
    replicaSet: ClusterResourceTypeByKind['ReplicaSet']
    previousReplicaSet: ClusterResourceTypeByKind['ReplicaSet']
  }
}

export interface DeploymentCreatedEvent extends BaseEvent {
  type: 'DeploymentCreated'
  payload: {
    deployment: ClusterResourceTypeByKind['Deployment']
  }
}

export interface DeploymentDeletedEvent extends BaseEvent {
  type: 'DeploymentDeleted'
  payload: {
    name: string
    namespace: string
    deletedDeployment: ClusterResourceTypeByKind['Deployment']
  }
}

export interface DeploymentUpdatedEvent extends BaseEvent {
  type: 'DeploymentUpdated'
  payload: {
    name: string
    namespace: string
    deployment: ClusterResourceTypeByKind['Deployment']
    previousDeployment: ClusterResourceTypeByKind['Deployment']
  }
}

export interface DaemonSetCreatedEvent extends BaseEvent {
  type: 'DaemonSetCreated'
  payload: {
    daemonSet: ClusterResourceTypeByKind['DaemonSet']
  }
}

export interface DaemonSetDeletedEvent extends BaseEvent {
  type: 'DaemonSetDeleted'
  payload: {
    name: string
    namespace: string
    deletedDaemonSet: ClusterResourceTypeByKind['DaemonSet']
  }
}

export interface DaemonSetUpdatedEvent extends BaseEvent {
  type: 'DaemonSetUpdated'
  payload: {
    name: string
    namespace: string
    daemonSet: ClusterResourceTypeByKind['DaemonSet']
    previousDaemonSet: ClusterResourceTypeByKind['DaemonSet']
  }
}

export interface StatefulSetCreatedEvent extends BaseEvent {
  type: 'StatefulSetCreated'
  payload: {
    statefulSet: ClusterResourceTypeByKind['StatefulSet']
  }
}

export interface StatefulSetDeletedEvent extends BaseEvent {
  type: 'StatefulSetDeleted'
  payload: {
    name: string
    namespace: string
    deletedStatefulSet: ClusterResourceTypeByKind['StatefulSet']
  }
}

export interface StatefulSetUpdatedEvent extends BaseEvent {
  type: 'StatefulSetUpdated'
  payload: {
    name: string
    namespace: string
    statefulSet: ClusterResourceTypeByKind['StatefulSet']
    previousStatefulSet: ClusterResourceTypeByKind['StatefulSet']
  }
}

export interface ServiceCreatedEvent extends BaseEvent {
  type: 'ServiceCreated'
  payload: {
    service: ClusterResourceTypeByKind['Service']
  }
}

export interface ServiceDeletedEvent extends BaseEvent {
  type: 'ServiceDeleted'
  payload: {
    name: string
    namespace: string
    deletedService: ClusterResourceTypeByKind['Service']
  }
}

export interface ServiceUpdatedEvent extends BaseEvent {
  type: 'ServiceUpdated'
  payload: {
    name: string
    namespace: string
    service: ClusterResourceTypeByKind['Service']
    previousService: ClusterResourceTypeByKind['Service']
  }
}

export interface EndpointSliceCreatedEvent extends BaseEvent {
  type: 'EndpointSliceCreated'
  payload: {
    endpointSlice: ClusterResourceTypeByKind['EndpointSlice']
  }
}

export interface EndpointSliceDeletedEvent extends BaseEvent {
  type: 'EndpointSliceDeleted'
  payload: {
    name: string
    namespace: string
    deletedEndpointSlice: ClusterResourceTypeByKind['EndpointSlice']
  }
}

export interface EndpointSliceUpdatedEvent extends BaseEvent {
  type: 'EndpointSliceUpdated'
  payload: {
    name: string
    namespace: string
    endpointSlice: ClusterResourceTypeByKind['EndpointSlice']
    previousEndpointSlice: ClusterResourceTypeByKind['EndpointSlice']
  }
}

export interface EndpointsCreatedEvent extends BaseEvent {
  type: 'EndpointsCreated'
  payload: {
    endpoints: ClusterResourceTypeByKind['Endpoints']
  }
}

export interface EndpointsDeletedEvent extends BaseEvent {
  type: 'EndpointsDeleted'
  payload: {
    name: string
    namespace: string
    deletedEndpoints: ClusterResourceTypeByKind['Endpoints']
  }
}

export interface EndpointsUpdatedEvent extends BaseEvent {
  type: 'EndpointsUpdated'
  payload: {
    name: string
    namespace: string
    endpoints: ClusterResourceTypeByKind['Endpoints']
    previousEndpoints: ClusterResourceTypeByKind['Endpoints']
  }
}

export interface EventCreatedEvent extends BaseEvent {
  type: 'EventCreated'
  payload: {
    event: ClusterResourceTypeByKind['Event']
  }
}

export interface EventDeletedEvent extends BaseEvent {
  type: 'EventDeleted'
  payload: {
    name: string
    namespace: string
    deletedEvent: ClusterResourceTypeByKind['Event']
  }
}

export interface EventUpdatedEvent extends BaseEvent {
  type: 'EventUpdated'
  payload: {
    name: string
    namespace: string
    event: ClusterResourceTypeByKind['Event']
    previousEvent: ClusterResourceTypeByKind['Event']
  }
}

export interface IngressCreatedEvent extends BaseEvent {
  type: 'IngressCreated'
  payload: {
    ingress: ClusterResourceTypeByKind['Ingress']
  }
}

export interface IngressDeletedEvent extends BaseEvent {
  type: 'IngressDeleted'
  payload: {
    name: string
    namespace: string
    deletedIngress: ClusterResourceTypeByKind['Ingress']
  }
}

export interface IngressUpdatedEvent extends BaseEvent {
  type: 'IngressUpdated'
  payload: {
    name: string
    namespace: string
    ingress: ClusterResourceTypeByKind['Ingress']
    previousIngress: ClusterResourceTypeByKind['Ingress']
  }
}

export interface IngressClassCreatedEvent extends BaseEvent {
  type: 'IngressClassCreated'
  payload: {
    ingressClass: ClusterResourceTypeByKind['IngressClass']
  }
}

export interface IngressClassDeletedEvent extends BaseEvent {
  type: 'IngressClassDeleted'
  payload: {
    name: string
    deletedIngressClass: ClusterResourceTypeByKind['IngressClass']
  }
}

export interface IngressClassUpdatedEvent extends BaseEvent {
  type: 'IngressClassUpdated'
  payload: {
    name: string
    ingressClass: ClusterResourceTypeByKind['IngressClass']
    previousIngressClass: ClusterResourceTypeByKind['IngressClass']
  }
}

export interface NetworkPolicyCreatedEvent extends BaseEvent {
  type: 'NetworkPolicyCreated'
  payload: {
    networkPolicy: ClusterResourceTypeByKind['NetworkPolicy']
  }
}

export interface NetworkPolicyDeletedEvent extends BaseEvent {
  type: 'NetworkPolicyDeleted'
  payload: {
    name: string
    namespace: string
    deletedNetworkPolicy: ClusterResourceTypeByKind['NetworkPolicy']
  }
}

export interface NetworkPolicyUpdatedEvent extends BaseEvent {
  type: 'NetworkPolicyUpdated'
  payload: {
    name: string
    namespace: string
    networkPolicy: ClusterResourceTypeByKind['NetworkPolicy']
    previousNetworkPolicy: ClusterResourceTypeByKind['NetworkPolicy']
  }
}

export interface GatewayClassCreatedEvent extends BaseEvent {
  type: 'GatewayClassCreated'
  payload: {
    gatewayClass: ClusterResourceTypeByKind['GatewayClass']
  }
}

export interface GatewayClassDeletedEvent extends BaseEvent {
  type: 'GatewayClassDeleted'
  payload: {
    name: string
    deletedGatewayClass: ClusterResourceTypeByKind['GatewayClass']
  }
}

export interface GatewayClassUpdatedEvent extends BaseEvent {
  type: 'GatewayClassUpdated'
  payload: {
    name: string
    gatewayClass: ClusterResourceTypeByKind['GatewayClass']
    previousGatewayClass: ClusterResourceTypeByKind['GatewayClass']
  }
}

export interface GatewayCreatedEvent extends BaseEvent {
  type: 'GatewayCreated'
  payload: {
    gateway: ClusterResourceTypeByKind['Gateway']
  }
}

export interface GatewayDeletedEvent extends BaseEvent {
  type: 'GatewayDeleted'
  payload: {
    name: string
    namespace: string
    deletedGateway: ClusterResourceTypeByKind['Gateway']
  }
}

export interface GatewayUpdatedEvent extends BaseEvent {
  type: 'GatewayUpdated'
  payload: {
    name: string
    namespace: string
    gateway: ClusterResourceTypeByKind['Gateway']
    previousGateway: ClusterResourceTypeByKind['Gateway']
  }
}

export interface HTTPRouteCreatedEvent extends BaseEvent {
  type: 'HTTPRouteCreated'
  payload: {
    httpRoute: ClusterResourceTypeByKind['HTTPRoute']
  }
}

export interface HTTPRouteDeletedEvent extends BaseEvent {
  type: 'HTTPRouteDeleted'
  payload: {
    name: string
    namespace: string
    deletedHTTPRoute: ClusterResourceTypeByKind['HTTPRoute']
  }
}

export interface HTTPRouteUpdatedEvent extends BaseEvent {
  type: 'HTTPRouteUpdated'
  payload: {
    name: string
    namespace: string
    httpRoute: ClusterResourceTypeByKind['HTTPRoute']
    previousHTTPRoute: ClusterResourceTypeByKind['HTTPRoute']
  }
}

export interface PersistentVolumeCreatedEvent extends BaseEvent {
  type: 'PersistentVolumeCreated'
  payload: {
    persistentVolume: ClusterResourceTypeByKind['PersistentVolume']
  }
}

export interface PersistentVolumeDeletedEvent extends BaseEvent {
  type: 'PersistentVolumeDeleted'
  payload: {
    name: string
    deletedPersistentVolume: ClusterResourceTypeByKind['PersistentVolume']
  }
}

export interface PersistentVolumeUpdatedEvent extends BaseEvent {
  type: 'PersistentVolumeUpdated'
  payload: {
    name: string
    persistentVolume: ClusterResourceTypeByKind['PersistentVolume']
    previousPersistentVolume: ClusterResourceTypeByKind['PersistentVolume']
  }
}

export interface PersistentVolumeClaimCreatedEvent extends BaseEvent {
  type: 'PersistentVolumeClaimCreated'
  payload: {
    persistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim']
  }
}

export interface PersistentVolumeClaimDeletedEvent extends BaseEvent {
  type: 'PersistentVolumeClaimDeleted'
  payload: {
    name: string
    namespace: string
    deletedPersistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim']
  }
}

export interface PersistentVolumeClaimUpdatedEvent extends BaseEvent {
  type: 'PersistentVolumeClaimUpdated'
  payload: {
    name: string
    namespace: string
    persistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim']
    previousPersistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim']
  }
}

export interface ServiceAccountCreatedEvent extends BaseEvent {
  type: 'ServiceAccountCreated'
  payload: {
    serviceAccount: ClusterResourceTypeByKind['ServiceAccount']
  }
}

export interface ServiceAccountDeletedEvent extends BaseEvent {
  type: 'ServiceAccountDeleted'
  payload: {
    name: string
    namespace: string
    deletedServiceAccount: ClusterResourceTypeByKind['ServiceAccount']
  }
}

export interface ServiceAccountUpdatedEvent extends BaseEvent {
  type: 'ServiceAccountUpdated'
  payload: {
    name: string
    namespace: string
    serviceAccount: ClusterResourceTypeByKind['ServiceAccount']
    previousServiceAccount: ClusterResourceTypeByKind['ServiceAccount']
  }
}

export interface RoleCreatedEvent extends BaseEvent {
  type: 'RoleCreated'
  payload: {
    role: ClusterResourceTypeByKind['Role']
  }
}

export interface RoleDeletedEvent extends BaseEvent {
  type: 'RoleDeleted'
  payload: {
    name: string
    namespace: string
    deletedRole: ClusterResourceTypeByKind['Role']
  }
}

export interface RoleUpdatedEvent extends BaseEvent {
  type: 'RoleUpdated'
  payload: {
    name: string
    namespace: string
    role: ClusterResourceTypeByKind['Role']
    previousRole: ClusterResourceTypeByKind['Role']
  }
}

export interface RoleBindingCreatedEvent extends BaseEvent {
  type: 'RoleBindingCreated'
  payload: {
    roleBinding: ClusterResourceTypeByKind['RoleBinding']
  }
}

export interface RoleBindingDeletedEvent extends BaseEvent {
  type: 'RoleBindingDeleted'
  payload: {
    name: string
    namespace: string
    deletedRoleBinding: ClusterResourceTypeByKind['RoleBinding']
  }
}

export interface RoleBindingUpdatedEvent extends BaseEvent {
  type: 'RoleBindingUpdated'
  payload: {
    name: string
    namespace: string
    roleBinding: ClusterResourceTypeByKind['RoleBinding']
    previousRoleBinding: ClusterResourceTypeByKind['RoleBinding']
  }
}

export interface ClusterRoleCreatedEvent extends BaseEvent {
  type: 'ClusterRoleCreated'
  payload: {
    clusterRole: ClusterResourceTypeByKind['ClusterRole']
  }
}

export interface ClusterRoleDeletedEvent extends BaseEvent {
  type: 'ClusterRoleDeleted'
  payload: {
    name: string
    deletedClusterRole: ClusterResourceTypeByKind['ClusterRole']
  }
}

export interface ClusterRoleUpdatedEvent extends BaseEvent {
  type: 'ClusterRoleUpdated'
  payload: {
    name: string
    clusterRole: ClusterResourceTypeByKind['ClusterRole']
    previousClusterRole: ClusterResourceTypeByKind['ClusterRole']
  }
}

export interface ClusterRoleBindingCreatedEvent extends BaseEvent {
  type: 'ClusterRoleBindingCreated'
  payload: {
    clusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding']
  }
}

export interface ClusterRoleBindingDeletedEvent extends BaseEvent {
  type: 'ClusterRoleBindingDeleted'
  payload: {
    name: string
    deletedClusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding']
  }
}

export interface ClusterRoleBindingUpdatedEvent extends BaseEvent {
  type: 'ClusterRoleBindingUpdated'
  payload: {
    name: string
    clusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding']
    previousClusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding']
  }
}

export interface NamespaceCreatedEvent extends BaseEvent {
  type: 'NamespaceCreated'
  payload: {
    namespace: ClusterResourceTypeByKind['Namespace']
  }
}

export interface NamespaceDeletedEvent extends BaseEvent {
  type: 'NamespaceDeleted'
  payload: {
    name: string
    deletedNamespace: ClusterResourceTypeByKind['Namespace']
  }
}

export interface NamespaceUpdatedEvent extends BaseEvent {
  type: 'NamespaceUpdated'
  payload: {
    name: string
    namespace: ClusterResourceTypeByKind['Namespace']
    previousNamespace: ClusterResourceTypeByKind['Namespace']
  }
}

export interface LeaseCreatedEvent extends BaseEvent {
  type: 'LeaseCreated'
  payload: {
    lease: ClusterResourceTypeByKind['Lease']
  }
}

export interface LeaseDeletedEvent extends BaseEvent {
  type: 'LeaseDeleted'
  payload: {
    name: string
    namespace: string
    deletedLease: ClusterResourceTypeByKind['Lease']
  }
}

export interface LeaseUpdatedEvent extends BaseEvent {
  type: 'LeaseUpdated'
  payload: {
    name: string
    namespace: string
    lease: ClusterResourceTypeByKind['Lease']
    previousLease: ClusterResourceTypeByKind['Lease']
  }
}

export interface StorageClassCreatedEvent extends BaseEvent {
  type: 'StorageClassCreated'
  payload: {
    storageClass: ClusterResourceTypeByKind['StorageClass']
  }
}

export interface StorageClassDeletedEvent extends BaseEvent {
  type: 'StorageClassDeleted'
  payload: {
    name: string
    deletedStorageClass: ClusterResourceTypeByKind['StorageClass']
  }
}

export interface StorageClassUpdatedEvent extends BaseEvent {
  type: 'StorageClassUpdated'
  payload: {
    name: string
    storageClass: ClusterResourceTypeByKind['StorageClass']
    previousStorageClass: ClusterResourceTypeByKind['StorageClass']
  }
}

export type GeneratedClusterCrudEvent =
  | PodCreatedEvent
  | PodDeletedEvent
  | PodUpdatedEvent
  | ConfigMapCreatedEvent
  | ConfigMapDeletedEvent
  | ConfigMapUpdatedEvent
  | ControllerRevisionCreatedEvent
  | ControllerRevisionDeletedEvent
  | ControllerRevisionUpdatedEvent
  | SecretCreatedEvent
  | SecretDeletedEvent
  | SecretUpdatedEvent
  | NodeCreatedEvent
  | NodeDeletedEvent
  | NodeUpdatedEvent
  | ReplicaSetCreatedEvent
  | ReplicaSetDeletedEvent
  | ReplicaSetUpdatedEvent
  | DeploymentCreatedEvent
  | DeploymentDeletedEvent
  | DeploymentUpdatedEvent
  | DaemonSetCreatedEvent
  | DaemonSetDeletedEvent
  | DaemonSetUpdatedEvent
  | StatefulSetCreatedEvent
  | StatefulSetDeletedEvent
  | StatefulSetUpdatedEvent
  | ServiceCreatedEvent
  | ServiceDeletedEvent
  | ServiceUpdatedEvent
  | EndpointSliceCreatedEvent
  | EndpointSliceDeletedEvent
  | EndpointSliceUpdatedEvent
  | EndpointsCreatedEvent
  | EndpointsDeletedEvent
  | EndpointsUpdatedEvent
  | EventCreatedEvent
  | EventDeletedEvent
  | EventUpdatedEvent
  | IngressCreatedEvent
  | IngressDeletedEvent
  | IngressUpdatedEvent
  | IngressClassCreatedEvent
  | IngressClassDeletedEvent
  | IngressClassUpdatedEvent
  | NetworkPolicyCreatedEvent
  | NetworkPolicyDeletedEvent
  | NetworkPolicyUpdatedEvent
  | GatewayClassCreatedEvent
  | GatewayClassDeletedEvent
  | GatewayClassUpdatedEvent
  | GatewayCreatedEvent
  | GatewayDeletedEvent
  | GatewayUpdatedEvent
  | HTTPRouteCreatedEvent
  | HTTPRouteDeletedEvent
  | HTTPRouteUpdatedEvent
  | PersistentVolumeCreatedEvent
  | PersistentVolumeDeletedEvent
  | PersistentVolumeUpdatedEvent
  | PersistentVolumeClaimCreatedEvent
  | PersistentVolumeClaimDeletedEvent
  | PersistentVolumeClaimUpdatedEvent
  | ServiceAccountCreatedEvent
  | ServiceAccountDeletedEvent
  | ServiceAccountUpdatedEvent
  | RoleCreatedEvent
  | RoleDeletedEvent
  | RoleUpdatedEvent
  | RoleBindingCreatedEvent
  | RoleBindingDeletedEvent
  | RoleBindingUpdatedEvent
  | ClusterRoleCreatedEvent
  | ClusterRoleDeletedEvent
  | ClusterRoleUpdatedEvent
  | ClusterRoleBindingCreatedEvent
  | ClusterRoleBindingDeletedEvent
  | ClusterRoleBindingUpdatedEvent
  | NamespaceCreatedEvent
  | NamespaceDeletedEvent
  | NamespaceUpdatedEvent
  | LeaseCreatedEvent
  | LeaseDeletedEvent
  | LeaseUpdatedEvent
  | StorageClassCreatedEvent
  | StorageClassDeletedEvent
  | StorageClassUpdatedEvent

export const createClusterEventMetadata = (
  source?: string
): BaseEvent['metadata'] => ({
  source: source || 'cluster',
  correlationId: crypto.randomUUID()
})

export const createClusterEventTimestamp = (): string => new Date().toISOString()

export const createPodCreatedEvent = (
  pod: ClusterResourceTypeByKind['Pod'],
  source?: string
): PodCreatedEvent => ({
  type: 'PodCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { pod }
})

export const createPodDeletedEvent = (
  name: string,
  namespace: string,
  deletedPod: ClusterResourceTypeByKind['Pod'],
  source?: string
): PodDeletedEvent => ({
  type: 'PodDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedPod }
})

export const createPodUpdatedEvent = (
  name: string,
  namespace: string,
  pod: ClusterResourceTypeByKind['Pod'],
  previousPod: ClusterResourceTypeByKind['Pod'],
  source?: string
): PodUpdatedEvent => ({
  type: 'PodUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, pod, previousPod }
})

export const createConfigMapCreatedEvent = (
  configMap: ClusterResourceTypeByKind['ConfigMap'],
  source?: string
): ConfigMapCreatedEvent => ({
  type: 'ConfigMapCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { configMap }
})

export const createConfigMapDeletedEvent = (
  name: string,
  namespace: string,
  deletedConfigMap: ClusterResourceTypeByKind['ConfigMap'],
  source?: string
): ConfigMapDeletedEvent => ({
  type: 'ConfigMapDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedConfigMap }
})

export const createConfigMapUpdatedEvent = (
  name: string,
  namespace: string,
  configMap: ClusterResourceTypeByKind['ConfigMap'],
  previousConfigMap: ClusterResourceTypeByKind['ConfigMap'],
  source?: string
): ConfigMapUpdatedEvent => ({
  type: 'ConfigMapUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, configMap, previousConfigMap }
})

export const createControllerRevisionCreatedEvent = (
  controllerRevision: ClusterResourceTypeByKind['ControllerRevision'],
  source?: string
): ControllerRevisionCreatedEvent => ({
  type: 'ControllerRevisionCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { controllerRevision }
})

export const createControllerRevisionDeletedEvent = (
  name: string,
  namespace: string,
  deletedControllerRevision: ClusterResourceTypeByKind['ControllerRevision'],
  source?: string
): ControllerRevisionDeletedEvent => ({
  type: 'ControllerRevisionDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedControllerRevision }
})

export const createControllerRevisionUpdatedEvent = (
  name: string,
  namespace: string,
  controllerRevision: ClusterResourceTypeByKind['ControllerRevision'],
  previousControllerRevision: ClusterResourceTypeByKind['ControllerRevision'],
  source?: string
): ControllerRevisionUpdatedEvent => ({
  type: 'ControllerRevisionUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, controllerRevision, previousControllerRevision }
})

export const createSecretCreatedEvent = (
  secret: ClusterResourceTypeByKind['Secret'],
  source?: string
): SecretCreatedEvent => ({
  type: 'SecretCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { secret }
})

export const createSecretDeletedEvent = (
  name: string,
  namespace: string,
  deletedSecret: ClusterResourceTypeByKind['Secret'],
  source?: string
): SecretDeletedEvent => ({
  type: 'SecretDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedSecret }
})

export const createSecretUpdatedEvent = (
  name: string,
  namespace: string,
  secret: ClusterResourceTypeByKind['Secret'],
  previousSecret: ClusterResourceTypeByKind['Secret'],
  source?: string
): SecretUpdatedEvent => ({
  type: 'SecretUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, secret, previousSecret }
})

export const createNodeCreatedEvent = (
  node: ClusterResourceTypeByKind['Node'],
  source?: string
): NodeCreatedEvent => ({
  type: 'NodeCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { node }
})

export const createNodeDeletedEvent = (
  name: string,
  deletedNode: ClusterResourceTypeByKind['Node'],
  source?: string
): NodeDeletedEvent => ({
  type: 'NodeDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedNode }
})

export const createNodeUpdatedEvent = (
  name: string,
  node: ClusterResourceTypeByKind['Node'],
  previousNode: ClusterResourceTypeByKind['Node'],
  source?: string
): NodeUpdatedEvent => ({
  type: 'NodeUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, node, previousNode }
})

export const createReplicaSetCreatedEvent = (
  replicaSet: ClusterResourceTypeByKind['ReplicaSet'],
  source?: string
): ReplicaSetCreatedEvent => ({
  type: 'ReplicaSetCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { replicaSet }
})

export const createReplicaSetDeletedEvent = (
  name: string,
  namespace: string,
  deletedReplicaSet: ClusterResourceTypeByKind['ReplicaSet'],
  source?: string
): ReplicaSetDeletedEvent => ({
  type: 'ReplicaSetDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedReplicaSet }
})

export const createReplicaSetUpdatedEvent = (
  name: string,
  namespace: string,
  replicaSet: ClusterResourceTypeByKind['ReplicaSet'],
  previousReplicaSet: ClusterResourceTypeByKind['ReplicaSet'],
  source?: string
): ReplicaSetUpdatedEvent => ({
  type: 'ReplicaSetUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, replicaSet, previousReplicaSet }
})

export const createDeploymentCreatedEvent = (
  deployment: ClusterResourceTypeByKind['Deployment'],
  source?: string
): DeploymentCreatedEvent => ({
  type: 'DeploymentCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { deployment }
})

export const createDeploymentDeletedEvent = (
  name: string,
  namespace: string,
  deletedDeployment: ClusterResourceTypeByKind['Deployment'],
  source?: string
): DeploymentDeletedEvent => ({
  type: 'DeploymentDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedDeployment }
})

export const createDeploymentUpdatedEvent = (
  name: string,
  namespace: string,
  deployment: ClusterResourceTypeByKind['Deployment'],
  previousDeployment: ClusterResourceTypeByKind['Deployment'],
  source?: string
): DeploymentUpdatedEvent => ({
  type: 'DeploymentUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deployment, previousDeployment }
})

export const createDaemonSetCreatedEvent = (
  daemonSet: ClusterResourceTypeByKind['DaemonSet'],
  source?: string
): DaemonSetCreatedEvent => ({
  type: 'DaemonSetCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { daemonSet }
})

export const createDaemonSetDeletedEvent = (
  name: string,
  namespace: string,
  deletedDaemonSet: ClusterResourceTypeByKind['DaemonSet'],
  source?: string
): DaemonSetDeletedEvent => ({
  type: 'DaemonSetDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedDaemonSet }
})

export const createDaemonSetUpdatedEvent = (
  name: string,
  namespace: string,
  daemonSet: ClusterResourceTypeByKind['DaemonSet'],
  previousDaemonSet: ClusterResourceTypeByKind['DaemonSet'],
  source?: string
): DaemonSetUpdatedEvent => ({
  type: 'DaemonSetUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, daemonSet, previousDaemonSet }
})

export const createStatefulSetCreatedEvent = (
  statefulSet: ClusterResourceTypeByKind['StatefulSet'],
  source?: string
): StatefulSetCreatedEvent => ({
  type: 'StatefulSetCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { statefulSet }
})

export const createStatefulSetDeletedEvent = (
  name: string,
  namespace: string,
  deletedStatefulSet: ClusterResourceTypeByKind['StatefulSet'],
  source?: string
): StatefulSetDeletedEvent => ({
  type: 'StatefulSetDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedStatefulSet }
})

export const createStatefulSetUpdatedEvent = (
  name: string,
  namespace: string,
  statefulSet: ClusterResourceTypeByKind['StatefulSet'],
  previousStatefulSet: ClusterResourceTypeByKind['StatefulSet'],
  source?: string
): StatefulSetUpdatedEvent => ({
  type: 'StatefulSetUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, statefulSet, previousStatefulSet }
})

export const createServiceCreatedEvent = (
  service: ClusterResourceTypeByKind['Service'],
  source?: string
): ServiceCreatedEvent => ({
  type: 'ServiceCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { service }
})

export const createServiceDeletedEvent = (
  name: string,
  namespace: string,
  deletedService: ClusterResourceTypeByKind['Service'],
  source?: string
): ServiceDeletedEvent => ({
  type: 'ServiceDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedService }
})

export const createServiceUpdatedEvent = (
  name: string,
  namespace: string,
  service: ClusterResourceTypeByKind['Service'],
  previousService: ClusterResourceTypeByKind['Service'],
  source?: string
): ServiceUpdatedEvent => ({
  type: 'ServiceUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, service, previousService }
})

export const createEndpointSliceCreatedEvent = (
  endpointSlice: ClusterResourceTypeByKind['EndpointSlice'],
  source?: string
): EndpointSliceCreatedEvent => ({
  type: 'EndpointSliceCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { endpointSlice }
})

export const createEndpointSliceDeletedEvent = (
  name: string,
  namespace: string,
  deletedEndpointSlice: ClusterResourceTypeByKind['EndpointSlice'],
  source?: string
): EndpointSliceDeletedEvent => ({
  type: 'EndpointSliceDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedEndpointSlice }
})

export const createEndpointSliceUpdatedEvent = (
  name: string,
  namespace: string,
  endpointSlice: ClusterResourceTypeByKind['EndpointSlice'],
  previousEndpointSlice: ClusterResourceTypeByKind['EndpointSlice'],
  source?: string
): EndpointSliceUpdatedEvent => ({
  type: 'EndpointSliceUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, endpointSlice, previousEndpointSlice }
})

export const createEndpointsCreatedEvent = (
  endpoints: ClusterResourceTypeByKind['Endpoints'],
  source?: string
): EndpointsCreatedEvent => ({
  type: 'EndpointsCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { endpoints }
})

export const createEndpointsDeletedEvent = (
  name: string,
  namespace: string,
  deletedEndpoints: ClusterResourceTypeByKind['Endpoints'],
  source?: string
): EndpointsDeletedEvent => ({
  type: 'EndpointsDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedEndpoints }
})

export const createEndpointsUpdatedEvent = (
  name: string,
  namespace: string,
  endpoints: ClusterResourceTypeByKind['Endpoints'],
  previousEndpoints: ClusterResourceTypeByKind['Endpoints'],
  source?: string
): EndpointsUpdatedEvent => ({
  type: 'EndpointsUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, endpoints, previousEndpoints }
})

export const createEventCreatedEvent = (
  event: ClusterResourceTypeByKind['Event'],
  source?: string
): EventCreatedEvent => ({
  type: 'EventCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { event }
})

export const createEventDeletedEvent = (
  name: string,
  namespace: string,
  deletedEvent: ClusterResourceTypeByKind['Event'],
  source?: string
): EventDeletedEvent => ({
  type: 'EventDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedEvent }
})

export const createEventUpdatedEvent = (
  name: string,
  namespace: string,
  event: ClusterResourceTypeByKind['Event'],
  previousEvent: ClusterResourceTypeByKind['Event'],
  source?: string
): EventUpdatedEvent => ({
  type: 'EventUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, event, previousEvent }
})

export const createIngressCreatedEvent = (
  ingress: ClusterResourceTypeByKind['Ingress'],
  source?: string
): IngressCreatedEvent => ({
  type: 'IngressCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { ingress }
})

export const createIngressDeletedEvent = (
  name: string,
  namespace: string,
  deletedIngress: ClusterResourceTypeByKind['Ingress'],
  source?: string
): IngressDeletedEvent => ({
  type: 'IngressDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedIngress }
})

export const createIngressUpdatedEvent = (
  name: string,
  namespace: string,
  ingress: ClusterResourceTypeByKind['Ingress'],
  previousIngress: ClusterResourceTypeByKind['Ingress'],
  source?: string
): IngressUpdatedEvent => ({
  type: 'IngressUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, ingress, previousIngress }
})

export const createIngressClassCreatedEvent = (
  ingressClass: ClusterResourceTypeByKind['IngressClass'],
  source?: string
): IngressClassCreatedEvent => ({
  type: 'IngressClassCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { ingressClass }
})

export const createIngressClassDeletedEvent = (
  name: string,
  deletedIngressClass: ClusterResourceTypeByKind['IngressClass'],
  source?: string
): IngressClassDeletedEvent => ({
  type: 'IngressClassDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedIngressClass }
})

export const createIngressClassUpdatedEvent = (
  name: string,
  ingressClass: ClusterResourceTypeByKind['IngressClass'],
  previousIngressClass: ClusterResourceTypeByKind['IngressClass'],
  source?: string
): IngressClassUpdatedEvent => ({
  type: 'IngressClassUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, ingressClass, previousIngressClass }
})

export const createNetworkPolicyCreatedEvent = (
  networkPolicy: ClusterResourceTypeByKind['NetworkPolicy'],
  source?: string
): NetworkPolicyCreatedEvent => ({
  type: 'NetworkPolicyCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { networkPolicy }
})

export const createNetworkPolicyDeletedEvent = (
  name: string,
  namespace: string,
  deletedNetworkPolicy: ClusterResourceTypeByKind['NetworkPolicy'],
  source?: string
): NetworkPolicyDeletedEvent => ({
  type: 'NetworkPolicyDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedNetworkPolicy }
})

export const createNetworkPolicyUpdatedEvent = (
  name: string,
  namespace: string,
  networkPolicy: ClusterResourceTypeByKind['NetworkPolicy'],
  previousNetworkPolicy: ClusterResourceTypeByKind['NetworkPolicy'],
  source?: string
): NetworkPolicyUpdatedEvent => ({
  type: 'NetworkPolicyUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, networkPolicy, previousNetworkPolicy }
})

export const createGatewayClassCreatedEvent = (
  gatewayClass: ClusterResourceTypeByKind['GatewayClass'],
  source?: string
): GatewayClassCreatedEvent => ({
  type: 'GatewayClassCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { gatewayClass }
})

export const createGatewayClassDeletedEvent = (
  name: string,
  deletedGatewayClass: ClusterResourceTypeByKind['GatewayClass'],
  source?: string
): GatewayClassDeletedEvent => ({
  type: 'GatewayClassDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedGatewayClass }
})

export const createGatewayClassUpdatedEvent = (
  name: string,
  gatewayClass: ClusterResourceTypeByKind['GatewayClass'],
  previousGatewayClass: ClusterResourceTypeByKind['GatewayClass'],
  source?: string
): GatewayClassUpdatedEvent => ({
  type: 'GatewayClassUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, gatewayClass, previousGatewayClass }
})

export const createGatewayCreatedEvent = (
  gateway: ClusterResourceTypeByKind['Gateway'],
  source?: string
): GatewayCreatedEvent => ({
  type: 'GatewayCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { gateway }
})

export const createGatewayDeletedEvent = (
  name: string,
  namespace: string,
  deletedGateway: ClusterResourceTypeByKind['Gateway'],
  source?: string
): GatewayDeletedEvent => ({
  type: 'GatewayDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedGateway }
})

export const createGatewayUpdatedEvent = (
  name: string,
  namespace: string,
  gateway: ClusterResourceTypeByKind['Gateway'],
  previousGateway: ClusterResourceTypeByKind['Gateway'],
  source?: string
): GatewayUpdatedEvent => ({
  type: 'GatewayUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, gateway, previousGateway }
})

export const createHTTPRouteCreatedEvent = (
  httpRoute: ClusterResourceTypeByKind['HTTPRoute'],
  source?: string
): HTTPRouteCreatedEvent => ({
  type: 'HTTPRouteCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { httpRoute }
})

export const createHTTPRouteDeletedEvent = (
  name: string,
  namespace: string,
  deletedHTTPRoute: ClusterResourceTypeByKind['HTTPRoute'],
  source?: string
): HTTPRouteDeletedEvent => ({
  type: 'HTTPRouteDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedHTTPRoute }
})

export const createHTTPRouteUpdatedEvent = (
  name: string,
  namespace: string,
  httpRoute: ClusterResourceTypeByKind['HTTPRoute'],
  previousHTTPRoute: ClusterResourceTypeByKind['HTTPRoute'],
  source?: string
): HTTPRouteUpdatedEvent => ({
  type: 'HTTPRouteUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, httpRoute, previousHTTPRoute }
})

export const createPersistentVolumeCreatedEvent = (
  persistentVolume: ClusterResourceTypeByKind['PersistentVolume'],
  source?: string
): PersistentVolumeCreatedEvent => ({
  type: 'PersistentVolumeCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { persistentVolume }
})

export const createPersistentVolumeDeletedEvent = (
  name: string,
  deletedPersistentVolume: ClusterResourceTypeByKind['PersistentVolume'],
  source?: string
): PersistentVolumeDeletedEvent => ({
  type: 'PersistentVolumeDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedPersistentVolume }
})

export const createPersistentVolumeUpdatedEvent = (
  name: string,
  persistentVolume: ClusterResourceTypeByKind['PersistentVolume'],
  previousPersistentVolume: ClusterResourceTypeByKind['PersistentVolume'],
  source?: string
): PersistentVolumeUpdatedEvent => ({
  type: 'PersistentVolumeUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, persistentVolume, previousPersistentVolume }
})

export const createPersistentVolumeClaimCreatedEvent = (
  persistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim'],
  source?: string
): PersistentVolumeClaimCreatedEvent => ({
  type: 'PersistentVolumeClaimCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { persistentVolumeClaim }
})

export const createPersistentVolumeClaimDeletedEvent = (
  name: string,
  namespace: string,
  deletedPersistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim'],
  source?: string
): PersistentVolumeClaimDeletedEvent => ({
  type: 'PersistentVolumeClaimDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedPersistentVolumeClaim }
})

export const createPersistentVolumeClaimUpdatedEvent = (
  name: string,
  namespace: string,
  persistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim'],
  previousPersistentVolumeClaim: ClusterResourceTypeByKind['PersistentVolumeClaim'],
  source?: string
): PersistentVolumeClaimUpdatedEvent => ({
  type: 'PersistentVolumeClaimUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, persistentVolumeClaim, previousPersistentVolumeClaim }
})

export const createServiceAccountCreatedEvent = (
  serviceAccount: ClusterResourceTypeByKind['ServiceAccount'],
  source?: string
): ServiceAccountCreatedEvent => ({
  type: 'ServiceAccountCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { serviceAccount }
})

export const createServiceAccountDeletedEvent = (
  name: string,
  namespace: string,
  deletedServiceAccount: ClusterResourceTypeByKind['ServiceAccount'],
  source?: string
): ServiceAccountDeletedEvent => ({
  type: 'ServiceAccountDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedServiceAccount }
})

export const createServiceAccountUpdatedEvent = (
  name: string,
  namespace: string,
  serviceAccount: ClusterResourceTypeByKind['ServiceAccount'],
  previousServiceAccount: ClusterResourceTypeByKind['ServiceAccount'],
  source?: string
): ServiceAccountUpdatedEvent => ({
  type: 'ServiceAccountUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, serviceAccount, previousServiceAccount }
})

export const createRoleCreatedEvent = (
  role: ClusterResourceTypeByKind['Role'],
  source?: string
): RoleCreatedEvent => ({
  type: 'RoleCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { role }
})

export const createRoleDeletedEvent = (
  name: string,
  namespace: string,
  deletedRole: ClusterResourceTypeByKind['Role'],
  source?: string
): RoleDeletedEvent => ({
  type: 'RoleDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedRole }
})

export const createRoleUpdatedEvent = (
  name: string,
  namespace: string,
  role: ClusterResourceTypeByKind['Role'],
  previousRole: ClusterResourceTypeByKind['Role'],
  source?: string
): RoleUpdatedEvent => ({
  type: 'RoleUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, role, previousRole }
})

export const createRoleBindingCreatedEvent = (
  roleBinding: ClusterResourceTypeByKind['RoleBinding'],
  source?: string
): RoleBindingCreatedEvent => ({
  type: 'RoleBindingCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { roleBinding }
})

export const createRoleBindingDeletedEvent = (
  name: string,
  namespace: string,
  deletedRoleBinding: ClusterResourceTypeByKind['RoleBinding'],
  source?: string
): RoleBindingDeletedEvent => ({
  type: 'RoleBindingDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedRoleBinding }
})

export const createRoleBindingUpdatedEvent = (
  name: string,
  namespace: string,
  roleBinding: ClusterResourceTypeByKind['RoleBinding'],
  previousRoleBinding: ClusterResourceTypeByKind['RoleBinding'],
  source?: string
): RoleBindingUpdatedEvent => ({
  type: 'RoleBindingUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, roleBinding, previousRoleBinding }
})

export const createClusterRoleCreatedEvent = (
  clusterRole: ClusterResourceTypeByKind['ClusterRole'],
  source?: string
): ClusterRoleCreatedEvent => ({
  type: 'ClusterRoleCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { clusterRole }
})

export const createClusterRoleDeletedEvent = (
  name: string,
  deletedClusterRole: ClusterResourceTypeByKind['ClusterRole'],
  source?: string
): ClusterRoleDeletedEvent => ({
  type: 'ClusterRoleDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedClusterRole }
})

export const createClusterRoleUpdatedEvent = (
  name: string,
  clusterRole: ClusterResourceTypeByKind['ClusterRole'],
  previousClusterRole: ClusterResourceTypeByKind['ClusterRole'],
  source?: string
): ClusterRoleUpdatedEvent => ({
  type: 'ClusterRoleUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, clusterRole, previousClusterRole }
})

export const createClusterRoleBindingCreatedEvent = (
  clusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding'],
  source?: string
): ClusterRoleBindingCreatedEvent => ({
  type: 'ClusterRoleBindingCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { clusterRoleBinding }
})

export const createClusterRoleBindingDeletedEvent = (
  name: string,
  deletedClusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding'],
  source?: string
): ClusterRoleBindingDeletedEvent => ({
  type: 'ClusterRoleBindingDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedClusterRoleBinding }
})

export const createClusterRoleBindingUpdatedEvent = (
  name: string,
  clusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding'],
  previousClusterRoleBinding: ClusterResourceTypeByKind['ClusterRoleBinding'],
  source?: string
): ClusterRoleBindingUpdatedEvent => ({
  type: 'ClusterRoleBindingUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, clusterRoleBinding, previousClusterRoleBinding }
})

export const createNamespaceCreatedEvent = (
  namespace: ClusterResourceTypeByKind['Namespace'],
  source?: string
): NamespaceCreatedEvent => ({
  type: 'NamespaceCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { namespace }
})

export const createNamespaceDeletedEvent = (
  name: string,
  deletedNamespace: ClusterResourceTypeByKind['Namespace'],
  source?: string
): NamespaceDeletedEvent => ({
  type: 'NamespaceDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedNamespace }
})

export const createNamespaceUpdatedEvent = (
  name: string,
  namespace: ClusterResourceTypeByKind['Namespace'],
  previousNamespace: ClusterResourceTypeByKind['Namespace'],
  source?: string
): NamespaceUpdatedEvent => ({
  type: 'NamespaceUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, previousNamespace }
})

export const createLeaseCreatedEvent = (
  lease: ClusterResourceTypeByKind['Lease'],
  source?: string
): LeaseCreatedEvent => ({
  type: 'LeaseCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { lease }
})

export const createLeaseDeletedEvent = (
  name: string,
  namespace: string,
  deletedLease: ClusterResourceTypeByKind['Lease'],
  source?: string
): LeaseDeletedEvent => ({
  type: 'LeaseDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, deletedLease }
})

export const createLeaseUpdatedEvent = (
  name: string,
  namespace: string,
  lease: ClusterResourceTypeByKind['Lease'],
  previousLease: ClusterResourceTypeByKind['Lease'],
  source?: string
): LeaseUpdatedEvent => ({
  type: 'LeaseUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, namespace, lease, previousLease }
})

export const createStorageClassCreatedEvent = (
  storageClass: ClusterResourceTypeByKind['StorageClass'],
  source?: string
): StorageClassCreatedEvent => ({
  type: 'StorageClassCreated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { storageClass }
})

export const createStorageClassDeletedEvent = (
  name: string,
  deletedStorageClass: ClusterResourceTypeByKind['StorageClass'],
  source?: string
): StorageClassDeletedEvent => ({
  type: 'StorageClassDeleted',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, deletedStorageClass }
})

export const createStorageClassUpdatedEvent = (
  name: string,
  storageClass: ClusterResourceTypeByKind['StorageClass'],
  previousStorageClass: ClusterResourceTypeByKind['StorageClass'],
  source?: string
): StorageClassUpdatedEvent => ({
  type: 'StorageClassUpdated',
  timestamp: createClusterEventTimestamp(),
  metadata: createClusterEventMetadata(source),
  payload: { name, storageClass, previousStorageClass }
})
